steps:
# Install dependencies
- name: 'python:3.8'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt']

# Run tests (if any)
# - name: 'python:3.8'
#   entrypoint: python
#   args: ['-m', 'unittest']

# Deploy to Google App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']